/**
 * Read and validate the packaged release compatibility manifest.
 *
 * The file is generated by `desktop/scripts/release-manifest.ts` on every build
 * and shipped via `extraResources`, so at runtime it lives at:
 *
 *   packaged → `process.resourcesPath/release-manifest.json`
 *   dev      → `<appPath>/resources/release-manifest.json`   (mirrored by buildResources)
 *
 * Invariants:
 *   - **Packaged builds fail CLOSED.** A missing or malformed manifest throws
 *     rather than degrading to "no version requirement". Silently treating it as
 *     absent would disable the compatibility gate precisely on the installs
 *     where it matters — a half-applied update.
 *   - **Dev builds fail OPEN.** `bun run dev` must keep working before anyone
 *     has run a full build, so a missing manifest there resolves to `null` and
 *     the gate is skipped.
 *   - Cached after the first successful read; the file cannot change during a
 *     single app lifetime (an update requires a restart).
 *
 * Non-obvious dep: reads `app.isPackaged` / `app.getAppPath()`, so this module
 * only loads inside the Electron main process.
 */
import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { app } from 'electron'
import { APP_PRODUCT_NAME } from '../shared/app-meta'
import { mainLog } from './logger'

/** Shape written by `scripts/release-manifest.ts`. Keep the two in sync. */
export interface ReleaseManifest {
  schema: 1
  desktopVersion: string
  requiredBackendVersion: string
}

const MANIFEST_BASENAME = 'release-manifest.json'

/** Raised when a packaged build cannot produce a usable manifest. */
export class ReleaseManifestUnavailable extends Error {
  constructor(
    public readonly searchedPath: string,
    reason: string,
  ) {
    super(
      `Release manifest is unusable (${reason}): ${searchedPath}. ` +
        'This build cannot verify which backend version it needs, so it will not ' +
        `connect to a daemon. Reinstall ${APP_PRODUCT_NAME}.`,
    )
    this.name = 'ReleaseManifestUnavailable'
  }
}

function manifestPath(): string {
  return app.isPackaged
    ? path.join(process.resourcesPath, MANIFEST_BASENAME)
    : path.join(app.getAppPath(), 'resources', MANIFEST_BASENAME)
}

function parseManifest(raw: string): ReleaseManifest {
  const parsed: unknown = JSON.parse(raw)
  if (typeof parsed !== 'object' || parsed === null) {
    throw new Error('not an object')
  }
  const candidate = parsed as Record<string, unknown>
  if (candidate.schema !== 1) {
    throw new Error(`unsupported schema ${String(candidate.schema)}`)
  }
  if (
    typeof candidate.desktopVersion !== 'string' ||
    typeof candidate.requiredBackendVersion !== 'string' ||
    candidate.desktopVersion.length === 0 ||
    candidate.requiredBackendVersion.length === 0
  ) {
    throw new Error('missing desktopVersion / requiredBackendVersion')
  }
  return {
    schema: 1,
    desktopVersion: candidate.desktopVersion,
    requiredBackendVersion: candidate.requiredBackendVersion,
  }
}

let cached: ReleaseManifest | null | undefined

/**
 * Return the packaged manifest, or `null` in a development build that has none.
 *
 * @throws {ReleaseManifestUnavailable} in a packaged build whose manifest is
 *   missing, unreadable or malformed.
 */
export function readReleaseManifest(): ReleaseManifest | null {
  if (cached !== undefined) return cached

  const file = manifestPath()
  if (!existsSync(file)) {
    if (app.isPackaged) throw new ReleaseManifestUnavailable(file, 'file not found')
    mainLog.warn(
      `[release-manifest] not found at ${file} — dev build, backend compatibility gate disabled. ` +
        'Run `bun run build` (or `bun run release-manifest`) to generate it.',
    )
    cached = null
    return cached
  }

  try {
    cached = parseManifest(readFileSync(file, 'utf-8'))
  } catch (err) {
    if (app.isPackaged) {
      throw new ReleaseManifestUnavailable(file, err instanceof Error ? err.message : String(err))
    }
    mainLog.warn('[release-manifest] malformed manifest in a dev build, gate disabled', err)
    cached = null
    return cached
  }

  mainLog.info(
    `[release-manifest] desktop ${cached.desktopVersion} requires backend ${cached.requiredBackendVersion}`,
  )
  return cached
}

/** Test seam — drops the memoized value so a test can swap the on-disk file. */
export function resetReleaseManifestCache(): void {
  cached = undefined
}
