/**
 * Tray-manager — system tray / menu bar icon for Amphi.
 *
 * Lives in Electron main. Three responsibilities:
 *   1. Display the daemon's status via the tray icon (online/offline/error)
 *      and a tooltip text.
 *   2. Provide a right-click context menu for quick actions:
 *        - "Open Main Window" → focusOrCreateMain (un-hides + focuses)
 *        - "Start Gateway" / "Stop Gateway" (mutually exclusive based on state)
 *        - "Restart Gateway"
 *        - "Cancel Start" is available while starting — otherwise during
 *          cliStart's 45s budget the menu is left with a single disabled
 *          label and the user has no way out except quitting completely
 *        - "Quit Completely" → quitWithDaemon: stop the gateway, then quit,
 *          asking first when other clients are attached (`app.quit()` fires
 *          before-quit, which is where isAppQuitting gets set)
 *   3. Subscribe to pythonClient.onState so the menu + icon track
 *      daemon transitions live.
 *
 * Icon assets: the brand logo plus a status dot in the lower-right corner,
 * generated by `bun run icons:tray` from `resources/source/icon-dark.svg` into
 * `tray-icons.generated.ts` (@1x 16px + @2x 32px). To change the icon, edit
 * that SVG and re-run the script; never hand-edit the generated file.
 *
 * Why the images are inlined base64 rather than PNGs read at runtime: the
 * packaging allowlist (`files` in `electron-builder.yml`) does not include
 * `resources/`, so an installed app has no image on disk to read — it works
 * fine in dev and shows an empty icon once installed. Full reasoning in the
 * header comment of `resources/generate-tray-icons.ts`.
 *
 * No macOS template image: a template image only consumes the alpha channel
 * and repaints the whole image in the system color, which would flatten the
 * status dot to black-and-white too and destroy the "see the gateway state at
 * a glance" requirement. We use a colored image instead (gradient background +
 * white glyph), which holds up on both light and dark menu bars.
 *
 * macOS note: we set `setIgnoreDoubleClickEvents(true)` so the menu
 * appears on left-click rather than requiring a deliberate right-
 * click — matches common menu-bar app UX (1Password, Slack, etc.).
 */

import { app, Menu, nativeImage, Tray } from 'electron'
import type { MenuItemConstructorOptions } from 'electron'
import { APP_PRODUCT_NAME } from '../shared/app-meta'
import { mt } from './i18n'
import { mainLog } from './logger'
import { pythonClient } from './python-client'
import {
  BackendState,
  type BackendSnapshot,
} from './python-client/types'
import { TRAY_ICONS, type TrayIconSet } from './tray-icons.generated'

/** Assemble a pair of @1x/@2x base64 PNGs into a single multi-scale nativeImage.
 *
 *  Both representations are required: with only the 16px one, the system
 *  upscales it into a blurry image on Retina; with only the 32px one, it is
 *  treated as 32 logical points on non-Retina and the icon bursts out of the
 *  menu bar. Use dataURL rather than addRepresentation({buffer}) — the latter
 *  wants a **raw bitmap**, and feeding it an encoded PNG silently yields an
 *  empty image. */
function toNativeImage(set: TrayIconSet) {
  const img = nativeImage.createFromDataURL(`data:image/png;base64,${set.x1}`)
  img.addRepresentation({ scaleFactor: 2, dataURL: `data:image/png;base64,${set.x2}` })
  return img
}

/** The three images are immutable, so build once and cache — `iconFor` runs on
 *  every health-probe flap via `pythonClient.onState`, and building on the fly
 *  would base64-decode two ~2.7KB PNGs each time.
 *
 *  Lazy rather than a module-level constant: this module is imported at the
 *  top of `main/index.ts`, before `app.whenReady()` has fired; the first
 *  access happens inside `TrayManager.init()` (after ready), so we don't have
 *  to bet on nativeImage being constructible before ready on every platform. */
const imageCache = new Map<keyof typeof TRAY_ICONS, Electron.NativeImage>()

function cachedImage(key: keyof typeof TRAY_ICONS) {
  const hit = imageCache.get(key)
  if (hit) return hit
  const img = toNativeImage(TRAY_ICONS[key])
  imageCache.set(key, img)
  return img
}

function iconFor(state: BackendState) {
  if (state === BackendState.Ready) return cachedImage('online')
  // `incompatible` shares the error icon rather than the offline one: a daemon
  // IS running, we just refuse to drive it. Showing it as stopped would send the
  // user looking for a gateway that is demonstrably up.
  if (state === BackendState.Unhealthy || state === BackendState.Incompatible) {
    return cachedImage('error')
  }
  // "Busy" must be distinguishable from "stopped". The CLI's readiness timeout
  // is 40s, and if the icon looked the same as the stopped state during that
  // window, the user could only guess at progress by repeatedly opening and
  // closing the tray menu — and on macOS the tray menu is a snapshot once
  // opened and never refreshes itself on state change, so the icon is the only
  // thing that moves during those 40 seconds.
  if (state === BackendState.Spawning || state === BackendState.Discovering) {
    return cachedImage('starting')
  }
  return cachedImage('offline')
}

function statusLabel(state: BackendState, version: string | null): string {
  switch (state) {
    case BackendState.Ready:
      return version ? mt('main.tray.status.ready', { version }) : mt('main.tray.status.readyNoVersion')
    case BackendState.Unhealthy:
      return mt('main.tray.status.unhealthy')
    case BackendState.Incompatible:
      return version
        ? mt('main.tray.status.incompatible', { version })
        : mt('main.tray.status.incompatibleNoVersion')
    case BackendState.Spawning:
      return mt('main.tray.status.spawning')
    case BackendState.Discovering:
      return mt('main.tray.status.discovering')
    case BackendState.Idle:
    case BackendState.Unavailable:
    default:
      return mt('main.tray.status.offline')
  }
}

/** Flatten and truncate error text to a single line — neither tooltips nor menu items can carry a multi-line stack. */
function briefError(message: string): string {
  const single = message.replace(/\s+/gu, ' ').trim()
  return single.length > 80 ? `${single.slice(0, 79)}…` : single
}

function tooltipFor(snap: BackendSnapshot): string {
  const head = statusLabel(snap.state, snap.endpoint?.version ?? null)
  const lines = [APP_PRODUCT_NAME, head]
  if (snap.endpoint?.baseUrl) lines.push(snap.endpoint.baseUrl)
  // The failure reason used to be shown nowhere: a failed start and a
  // user-initiated stop looked exactly the same in the menu (both "○ Gateway
  // not running"), leaving the user with no hint that they should check the log.
  if (snap.lastError) lines.push(`⚠ ${briefError(snap.lastError)}`)
  return lines.join('\n')
}

/** Callbacks the tray needs to delegate to the rest of main. */
export interface TrayCallbacks {
  /** Bring the main window to the front, recreating if destroyed. */
  openMain: () => void
  /** Full quit — stops the daemon (asking first when other clients are
   *  attached) and then exits. See `quit-with-daemon.ts`. */
  quitApp: () => void
  /** Reveal the daemon log — the tray's error line links here. */
  openLogs: () => void
}

export class TrayManager {
  private tray: Tray | null = null
  private unsubscribeState: (() => void) | null = null
  private callbacks: TrayCallbacks | null = null
  /** In-flight guard for the "Start Gateway" item — see its `click` handler. */
  private starting = false

  /** Idempotent. Safe to call multiple times; second+ calls no-op. */
  init(callbacks: TrayCallbacks): void {
    if (this.tray) return
    this.callbacks = callbacks

    const snap = pythonClient.snapshot()
    this.tray = new Tray(iconFor(snap.state))
    this.tray.setToolTip(tooltipFor(snap))

    // Left-click on macOS opens the menu directly (matches menu-bar app UX).
    // Without this, single-click does nothing and only right-click works.
    if (process.platform === 'darwin') {
      this.tray.setIgnoreDoubleClickEvents(true)
    } else {
      // On Windows/Linux, left-click opens the main window directly.
      // Right-click still opens the menu via the OS default.
      this.tray.on('click', () => callbacks.openMain())
    }

    this.rebuildMenu(snap)

    this.unsubscribeState = pythonClient.onState((next) => {
      if (!this.tray) return
      this.tray.setImage(iconFor(next.state))
      this.tray.setToolTip(tooltipFor(next))
      this.rebuildMenu(next)
    })

    mainLog.info('[tray] initialized')
  }

  /**
   * Redraw the menu and tooltip from the current daemon state.
   *
   * For changes that alter the *presentation* rather than the state — today only a display
   * language switch (`gui-settings.applyLocale`). The menu handed to the OS never re-reads
   * its labels, so without an explicit rebuild the tray would keep the previous language
   * until the daemon happened to change state. A no-op before `init`, so the boot-time
   * `applyLocale` that runs before the tray exists is harmless.
   */
  refreshMenu(): void {
    if (!this.tray) return
    const snap = pythonClient.snapshot()
    this.tray.setToolTip(tooltipFor(snap))
    this.rebuildMenu(snap)
  }

  destroy(): void {
    if (this.unsubscribeState) {
      this.unsubscribeState()
      this.unsubscribeState = null
    }
    if (this.tray) {
      this.tray.destroy()
      this.tray = null
    }
    this.callbacks = null
  }

  private rebuildMenu(snap: BackendSnapshot): void {
    if (!this.tray || !this.callbacks) return
    const cb = this.callbacks

    // Status line: non-interactive label echoing the icon/tooltip state so
    // users get a textual confirmation when they open the menu.
    const items: MenuItemConstructorOptions[] = [
      {
        label: statusLabel(snap.state, snap.endpoint?.version ?? null),
        enabled: false,
      },
    ]
    // The failure reason gets its own line. It's clickable (opens the log) —
    // an 80-character truncated message is usually only enough to say "which
    // category is it: environment / port / permissions", and the real stack
    // still has to be read from the log.
    if (snap.lastError) {
      items.push({
        label: `⚠ ${briefError(snap.lastError)}`,
        click: () => cb.openLogs(),
      })
    }
    items.push(
      { type: 'separator' },
      {
        label: mt('main.tray.openWindow'),
        click: () => cb.openMain(),
      },
      { type: 'separator' },
    )

    if (snap.state === BackendState.Incompatible) {
      // Only "restart" — that is the one action that can resolve a mismatch, and
      // it is the same action the main window's blocking screen offers. Stop
      // would leave the user with no gateway and no way back; start would
      // re-adopt the same daemon and land here again.
      items.push({
        label: mt('main.tray.restartForUpdate'),
        click: () => {
          void pythonClient.restart().catch((err: unknown) => {
            mainLog.warn('[tray] restart after version mismatch failed', err)
          })
        },
      })
    } else if (snap.state === BackendState.Ready || snap.state === BackendState.Unhealthy) {
      items.push({
        label: mt('main.tray.stopGateway'),
        click: () => {
          void pythonClient.stopDaemon().catch((err: unknown) => {
            mainLog.warn('[tray] stopDaemon failed', err)
          })
        },
      })
      items.push({
        label: mt('main.tray.restartGateway'),
        click: () => {
          void pythonClient.restart().catch((err: unknown) => {
            mainLog.warn('[tray] restart failed', err)
          })
        },
      })
    } else if (snap.state === BackendState.Spawning || snap.state === BackendState.Discovering) {
      items.push({
        label: snap.state === BackendState.Spawning ? mt('main.tray.starting') : mt('main.tray.discovering'),
        enabled: false,
      })
      // The escape hatch. cliStart's budget is 45s, and without a way out
      // during it the user faces a menu with only "Open Main Window" / "Quit
      // Completely" left — so when it hangs, the only option is to quit the
      // entire app.
      items.push({
        label: mt('main.tray.cancelStart'),
        click: () => {
          void pythonClient.stopDaemon().catch((err: unknown) => {
            mainLog.warn('[tray] cancel start failed', err)
          })
        },
      })
    } else {
      // idle / unavailable
      items.push({
        label: mt('main.tray.startGateway'),
        // Re-entrancy guard: PythonClient.start() has no in-flight guard of
        // its own, so two quick clicks would run the discovery flow twice
        // concurrently (GatewayBootGate has a `starting` guard; the tray does not).
        enabled: !this.starting,
        click: () => {
          if (this.starting) return
          this.starting = true
          void pythonClient
            .start()
            .catch((err: unknown) => mainLog.warn('[tray] start failed', err))
            .finally(() => {
              this.starting = false
              // The state hasn't necessarily changed when start() returns (a
              // failure is still unavailable), so onState may not fire —
              // rebuild explicitly, otherwise "Start Gateway" stays disabled forever.
              this.rebuildMenu(pythonClient.snapshot())
            })
        },
      })
    }

    items.push({ type: 'separator' })
    items.push({
      label: mt('main.tray.quitApp'),
      click: () => cb.quitApp(),
    })

    this.tray.setContextMenu(Menu.buildFromTemplate(items))
  }
}

/** Module-level singleton, mirroring pythonClient's pattern. */
export const trayManager = new TrayManager()

// Best-effort cleanup if app exits via signal before before-quit fires.
app.on('quit', () => {
  trayManager.destroy()
})
