import { resolve } from "node:path";

import { promptPythonExecutable, promptSourceFingerprint } from "../server/prompt/source";

const repositoryRoot = resolve(import.meta.dir, "../..");
const fingerprint = await promptSourceFingerprint(repositoryRoot);
const outputPath = resolve(import.meta.dir, "../server/prompt/personas.generated.ts");
const python = String.raw`
import json
import sys
import types
from pathlib import Path

sys.dont_write_bytecode = True
repository_root = Path(sys.argv[1]).resolve()
sys.path.insert(0, str(repository_root))
import src
package = types.ModuleType("src.amphi_agent")
package.__path__ = [str(repository_root / "src/amphi_agent")]
package.__package__ = "src.amphi_agent"
sys.modules["src.amphi_agent"] = package
from src.amphi_agent.prompts.build.clarify import CLARIFY_PERSONA
from src.amphi_agent.prompts.build.explore import EXPLORE_PERSONA
from src.amphi_agent.prompts.build.generate import GENERATE_PERSONA
from src.amphi_agent.prompts.build.verify import VERIFY_PERSONA
from src.amphi_agent.prompts.normal.main import PERSONA
from src.amphi_agent.prompts.normal.subagent import SUB_AGENT_PERSONA
from src.amphi_agent.prompts.shared import _SUB_AGENT_GUIDANCE
from src.amphi_agent.prompts.turn_failed import TURN_FAILED_MESSAGE
from src.amphi_agent.prompts.workflow.execute import WORKFLOW_PERSONA
json.dump({
    "main": PERSONA,
    "child": SUB_AGENT_PERSONA,
    "clarify": CLARIFY_PERSONA,
    "explore": EXPLORE_PERSONA,
    "generate": GENERATE_PERSONA,
    "verify": VERIFY_PERSONA,
    "workflowExecute": WORKFLOW_PERSONA,
    "subAgentGuidance": _SUB_AGENT_GUIDANCE,
    "turnFailedMessage": TURN_FAILED_MESSAGE,
}, sys.stdout, ensure_ascii=False)
`;

const result = Bun.spawnSync([promptPythonExecutable(repositoryRoot), "-c", python, repositoryRoot]);
if (result.exitCode !== 0) {
  throw new Error(`Could not snapshot prompt modules:\n${result.stderr.toString()}`);
}

const hash = fingerprint.sha256;
const personas = JSON.parse(result.stdout.toString()) as Record<string, string>;
const generated = `// Generated by scripts/snapshot-personas.ts. Do not edit by hand.\n`
  + `// Source graph: ${fingerprint.paths.join(", ")} (SHA-256 ${hash})\n\n`
  + `export const PERSONA_SOURCE_PATH = "src/amphi_agent/prompts" as const;\n`
  + `export const PERSONA_SOURCE_PATHS = ${JSON.stringify(fingerprint.paths)} as const;\n`
  + `export const PERSONA_SOURCE_SHA256 = ${JSON.stringify(hash)} as const;\n`
  + `export const PERSONA_SOURCE_VERSION = ${JSON.stringify(`prompts@${hash.slice(0, 12)}`)} as const;\n\n`
  + `export const PERSONA_SOURCE_SNAPSHOT = ${JSON.stringify(personas, null, 2)} as const;\n`;

await Bun.write(outputPath, generated);
console.log(`Wrote ${outputPath}`);
