import { resolve } from "node:path";

import { promptPythonExecutable, promptSourceFingerprint } from "../server/prompt/source";

const repositoryRoot = resolve(import.meta.dir, "../..");
const fingerprint = await promptSourceFingerprint(repositoryRoot);
const sourcePath = resolve(repositoryRoot, fingerprint.paths[0]);
const outputPath = resolve(import.meta.dir, "../server/prompt/personas.generated.ts");
const python = String.raw`
import importlib.util
import json
import sys
import types
from pathlib import Path

sys.dont_write_bytecode = True
source_path = Path(sys.argv[1]).resolve()
sys.path.insert(0, str(source_path.parents[2]))
import src
package = types.ModuleType("src.amphi_agent")
package.__path__ = [str(source_path.parent)]
package.__package__ = "src.amphi_agent"
sys.modules["src.amphi_agent"] = package
spec = importlib.util.spec_from_file_location("src.amphi_agent._prompt_snapshot", source_path)
module = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = module
assert spec.loader is not None
spec.loader.exec_module(module)
json.dump({
    "main": module.PERSONA,
    "child": module.SUB_AGENT_PERSONA,
    "clarify": module.CLARIFY_PERSONA,
    "explore": module.EXPLORE_PERSONA,
    "generate": module.GENERATE_PERSONA,
    "verify": module.VERIFY_PERSONA,
    "workflowExecute": module.WORKFLOW_PERSONA,
    "subAgentGuidance": module._SUB_AGENT_GUIDANCE,
    "turnFailedMessage": module.TURN_FAILED_MESSAGE,
}, sys.stdout, ensure_ascii=False)
`;

const result = Bun.spawnSync([promptPythonExecutable(repositoryRoot), "-c", python, sourcePath]);
if (result.exitCode !== 0) {
  throw new Error(`Could not snapshot _prompt.py:\n${result.stderr.toString()}`);
}

const hash = fingerprint.sha256;
const personas = JSON.parse(result.stdout.toString()) as Record<string, string>;
const generated = `// Generated by scripts/snapshot-personas.ts. Do not edit by hand.\n`
  + `// Source graph: ${fingerprint.paths.join(", ")} (SHA-256 ${hash})\n\n`
  + `export const PERSONA_SOURCE_PATH = "src/amphi_agent/_prompt.py" as const;\n`
  + `export const PERSONA_SOURCE_PATHS = ${JSON.stringify(fingerprint.paths)} as const;\n`
  + `export const PERSONA_SOURCE_SHA256 = ${JSON.stringify(hash)} as const;\n`
  + `export const PERSONA_SOURCE_VERSION = ${JSON.stringify(`_prompt.py@${hash.slice(0, 12)}`)} as const;\n\n`
  + `export const PERSONA_SOURCE_SNAPSHOT = ${JSON.stringify(personas, null, 2)} as const;\n`;

await Bun.write(outputPath, generated);
console.log(`Wrote ${outputPath}`);
