from typing import TYPE_CHECKING

import httpx

if TYPE_CHECKING:
    from src.amphi_service._app import ServiceApp


async def test_auth_boundary(service_app: "ServiceApp", service_client: httpx.AsyncClient) -> None:
    """Final HTTP access policy:

    {
      "public": ["GET /api/gateway/health"],
      "protected": {
        "GET /sessions": {
          "missing_token": 401,
          "invalid_token": 401,
          "valid_token": 200
        }
      }
    }

    Checks:
    1. The health endpoint remains available before a client has a token.
    2. Protected Handler routes reject missing and invalid bearer tokens.
    3. The token generated by this Service instance grants access.
    """
    transport = httpx.ASGITransport(app=service_app.app, raise_app_exceptions=True)
    async with httpx.AsyncClient(transport=transport, base_url="http://127.0.0.1") as public_client:
        # Check 1: The health endpoint remains available before a client has a token.
        health = await public_client.get("/api/gateway/health")
        assert health.status_code == 200
        assert health.json()["status"] == "ok"
        assert health.json()["version"]
        assert health.json()["started_at"]

        # Check 2: Protected Handler routes reject missing and invalid bearer tokens.
        missing = await public_client.get("/sessions")
        invalid = await public_client.get(
            "/sessions",
            headers={"Authorization": "Bearer invalid-token"},
        )
        assert missing.status_code == 401
        assert missing.json() == {"detail": "Missing or malformed Authorization header."}
        assert missing.headers["www-authenticate"] == "Bearer"
        assert invalid.status_code == 401
        assert invalid.json() == {"detail": "Invalid bearer token."}
        assert invalid.headers["www-authenticate"] == "Bearer"

    # Check 3: The token generated by this Service instance grants access.
    authorized = await service_client.get("/sessions")
    assert authorized.status_code == 200
    assert authorized.json() == []


async def test_client_registry(service_client: httpx.AsyncClient) -> None:
    """Final gateway state:

    {
      "connected_clients_count": 1,
      "clients": [
        {
          "client_id": "desktop-client",
          "client_type": "gui",
          "user_agent": "handler-test-client"
        }
      ]
    }

    Checks:
    1. Client headers register the caller before Gateway info is produced.
    2. The clients endpoint exposes the same non-secret client projection.
    """
    headers = {
        "X-Client-Id": "desktop-client",
        "X-Client-Type": "gui",
        "User-Agent": "handler-test-client",
    }

    # Check 1: Client headers register the caller before Gateway info is produced.
    response = await service_client.get("/api/gateway/info", headers=headers)
    assert response.status_code == 200
    info = response.json()
    assert info["host"] == "127.0.0.1"
    assert info["port"] == 0
    assert info["ws_path"] == "/ws"
    assert info["connected_clients_count"] == 1
    assert info["uptime_seconds"] >= 0
    assert set(info["agent_env"]) == {"status", "error"}

    # Check 2: The clients endpoint exposes the same non-secret client projection.
    response = await service_client.get("/api/gateway/clients", headers=headers)
    assert response.status_code == 200
    clients = response.json()
    assert len(clients) == 1
    assert clients[0]["client_id"] == "desktop-client"
    assert clients[0]["client_type"] == "gui"
    assert clients[0]["user_agent"] == "handler-test-client"
    assert clients[0]["connected_at"] <= clients[0]["last_seen"]
