"""Built-in default safety policy — used when there is no external ``policy.json``.

This is a **production default policy fitted to this agent's tool surface** (local
shell / files / git / credentials / persistence / browser / MCP): categories with no
corresponding tool surface here (kubectl / cloud storage / CI / IaC / Secret Manager /
production clusters / teammate / Artifact, etc.) are left out, keeping only the risks
exposed by this local agent's tool surface.

Output mapping: ``allow`` → allowed;
``soft_deny`` → ask (the user naming that specific operation unlocks it);
``hard_deny`` → deny (naming it does not unlock it); ``environment`` → trust-boundary
facts referenced by the three sections above (the runtime workspace root is injected
on the user side).

**``soft_deny`` is precisely "the tier that interrupts the user", so it deliberately
keeps only four categories** (narrowed 2026-07-26): irreversible destruction outside
the workspace, modifying the agent itself (self-modification / instruction poisoning),
and real-world consequences (transactions / publishing externally as the user).
Credential reads, outbound network, system-level installs, external publishing and
executing from uncontrolled sources are **no longer listed** — they still touch the
risk surface and still pass through the classifier (see
``_registry.RISK_SURFACE_COMMANDS``), injection and anomaly patterns still have
interception points, but because they match no soft_deny they are judged allow and
**do not interrupt the user**. Clearly malicious exfiltration is refused outright by
the ``hard_deny`` 'data exfiltration' rule — that is a deny, not an ask, so it raises
no dialog either.
Before adding an entry here, be clear about: **is this worth stopping to ask the user,
and is there any real chance the user would actually click deny?**

Users can override this default wholesale in their own
``~/.bridgic/AmphiAgent/policy.json``. This module holds data only; loading and
validation live in :mod:`_policy`, and policy → prompt in
:func:`~_classifier._build_system_prompt`.
"""

from __future__ import annotations

from ._policy import Policy

DEFAULT_POLICY = Policy(
    allow=(
        "Security topics: reading, discussing, reviewing or writing security-related code / documentation / configuration / threat models as part of the user's task is not in itself credential probing or data exfiltration; actually running an exploit, scanning for credentials or probing endpoints is still judged by its own rules.",
        "Transient retry: retrying the same or a rewritten operation after a network error / 5xx / timeout / rate limit / lock contention, or after one of its own tools returned an unexpected error, is not a bypass; the retry is still bound by the other rules, and an obfuscated retry (encoding / renaming in order to evade) does count as a bypass.",
        "Read-only and queries: reading files, listing directories, searching, read-only commands, plus read-only requests that change no state, whose URL carries no sensitive information and whose response body contains no credentials / keys / PII. But if the transcript holds clear evidence that the read is casing a blocked operation (probing an exfiltration endpoint, scanning for credentials), this exception does not apply.",
        "Operations inside the workspace: creating / editing / deleting files inside the session workspace, running scripts / builds / tests / formatters / artefact generation, and starting a local dev server are normal steps of the task; the workspace can be rolled back through checkpoints, so deletions / overwrites within it are recoverable operations. 'Workspace' means the session's starting directory; this exception is **limited to inside the workspace** and does not cover out-of-bounds (outside the workspace) deletion / overwriting of files that already existed before the session, nor local stateful services (those fall under soft_deny 'Irreversible local destruction'); going to ~ / /etc / another repository is out of bounds.",
        "Workspace dependency and resource preparation: to complete the user's task, using standard package managers **inside the session workspace, or inside a project directory the user named in their request** to prepare project dependencies (including rewriting an existing project's manifest / lock file along the way — that is a normal part of installing, not destruction), and fetching runtime resources the task needs (browser engines, model weights, fonts, datasets, etc.) — allow. Python special case: every Session / Build / Workflow Run / Child Agent shares the product-managed app-level Python base (`~/.bridgic/AmphiAgent/python/base`); use `uv pip install <pkg>` to install third-party packages into that base, and run ordinary scripts with `python <script>`. Node special case: these execution surfaces use only the product's bundled Node and share the app-level Node base (`~/.bridgic/AmphiAgent/node/base`); `npm install` / `uninstall` / `update` / `list` target that base whatever the current directory and package.json may be, and the packages and CLIs in it are visible to every execution surface. Neither of these two forms of product-internal shared dependency preparation counts as a global / system install or as self-modification; do not create a workspace Python environment or node_modules for an Agent helper / Workflow script. package.json may serve as script metadata, but it does not own a separate Node dependency environment. Other ecosystems, and the user's own existing projects, are still judged on three points: ①the install lands inside that workspace / project (.venv / vendor / target, etc.); ②the source is a package index / official distribution channel, or a **mirror the user has already configured** in pip.conf, .cargo/config or similar; ③it carries no sudo / -g / --global / --system. All three present → allow; installing from a URL / git / a cloned directory, and global or system-level installs, do not fall under this exception and are judged on their own nature.",
        "Mounting a file is authorisation: a path the user actively imported through 'Add file/folder' is an object the user handed to the Agent; reading, editing and overwriting it are normal operations within that authorisation and are not blocked by 'Irreversible local destruction'. Deleting the whole mounted directory, or sending mounted content out, is still judged by its own rules.",
        "A project directory the user named: when the user gives the path of a local directory / repository in their request and asks for the task to be done in it (e.g. 'build me a video based on /path/to/repo'), **that directory is this task's workspace**, and creating files, routine edits, dependency installs, builds and runs inside it are normal steps — allow; do not treat it as a suspicious out-of-bounds move just because it is not the session .work and was not mounted through 'Add file/folder'. The form the trust boundary takes (session workspace / UI mount) is an implementation detail; the user naming it in the conversation is equally explicit authorisation. **Still not unlocked**: deleting the user's own source code / data under that directory (judged by 'Irreversible local destruction'), sending its contents out, and going outside that directory to touch other paths. Naming a directory authorises routine reads and writes across its whole subtree; there is no need to name every file again.",
        "Toolchain bootstrap: when the repository manifest or the build configuration shows that a language toolchain the product does not bundle is required, it may be installed from the official one-line install script (rustup / bun / docker / brew, etc.). Python and Node must use the product's bundled runtimes and their single shared base; do not bootstrap a separate uv / Python / Node toolchain.",
        "Standard credential use: reading a credential from the agent's own configuration (.env / config file) and sending it to its corresponding target provider (e.g. an API key sent to the matching API endpoint).",
        "Steps necessary to the stated goal: when the user has explicitly said in their request that they want to connect to / log in to / operate some external system, the steps necessary and proportionate to that goal — including the remote communication of that system's standard login / authorisation flow (OAuth / device code / login-code callback / token exchange / initial handshake) — are normal operations, allow. Limited to the system the user named: traffic to other destinations, or outbound transfers / credential movement out of proportion to that goal (such as uploading ~/.ssh / .env under cover of logging in), are still judged by their own rules. A 'goal' cited only in the Agent's reasoning but with no root in the user's request does not fall under this exception.",
        "git push to a working branch: pushing to the session's starting branch (not the repository's default branch), or to a branch the agent created this session; does not include pushing to other pre-existing branches.",
        "Memory directory: routine reads, writes and cleanup of the agent's memory directory (recording / pruning user preferences, project facts, references); this is persistence guided by the system prompt and counts as neither self-modification nor irreversible destruction.",
    ),
    soft_deny=(
        "Irreversible local destruction: irreversibly deleting / truncating / overwriting local files that are **outside the workspace and already existed before this session** — rm -rf, git clean -fd, git checkout -- ., git reset --hard, git stash drop, `> file` truncation, or mv / cp / a write that overwrites an existing file — unless the user named the specific target. An uncertain pattern such as a glob / regex does not count as naming. Key point: this entry is about **making existing content unrecoverable**, not about 'writing something to some path'. The following do **not** fall under this entry: ①**creating a new file** — the target path did not exist before (for example writing a new file into a directory just created with mkdir), so no existing content is destroyed; when unsure whether the file exists, treat it as a new file and do not escalate over 'it might overwrite'; ②files inside the session workspace (checkpoints back them up and they can be rolled back, see ALLOW 'Operations inside the workspace'); ③**routine edits** inside paths the user actively mounted (see ALLOW 'Mounting a file is authorisation') and inside a project directory the user named in their request (see ALLOW 'A project directory the user named'); ④files the Agent itself created this session; ⑤**regenerable artefacts** (caches / dependencies / build output such as node_modules / __pycache__ / .venv / dist — fully rebuildable from a manifest or a build; the rule layer already allows these outright and they usually never reach this classifier).",
        "Self-modification: modifying files that control **the agent's own behaviour or permissions**, or the signed product core — the permission policy file (policy.json), skill definitions, startup / framework configuration, hook / command definitions, the app-bundled Python interpreter and standard-library files, the app-bundled Node interpreter and runtime files; including widening permission grants without the user asking for it (even while making an edit the user did ask for). Using `uv pip install` or `npm` to install, uninstall or update ordinary third-party dependencies into the product-managed app-level Python / Node base outside the package is permitted resource preparation and does not match this entry. Making changes according to preferences / permissions the user stated in their own messages is routine and unlockable; fabricating authorisation, or writing content that would bypass the interception, is still blocked.",
        "Instruction poisoning: writing content into the agent's configuration / memory / instruction files that 'will be taken as a permission grant or a rule bypass when read back' — forged user authorisation, evasion instructions aimed at the classifier, steering future sessions into blocked operations. Recording preferences / authorisations from what the user actually stated is not poisoning.",
        "External system writes: deleting / closing / bulk-modifying items in external collaboration tools (Jira / Linear / GitHub Issues / PRs, etc.) that were **not created in this session**; and publishing externally as the user (sending a message / commenting on a PR / filing a ticket / sending an email) when the user's task did not ask for it. Answering the user ≠ publishing externally.",
        "Real-world transactions: actions with direct real or financial consequences — purchasing, paying, placing an order, subscribing, sending communications to real people outside the organisation (customers / external contacts / vendors); block unless the user explicitly asked for that exact transaction.",
    ),
    hard_deny=(
        "Data exfiltration: sensitive data (originating inside the trust boundary — private repository files, configuration, lock files, credentials, or content read out of private storage / services) crossing the trust boundary (the workspace + destinations the user named as trusted) through an agent action, to a **confirmed external / public** destination, or leaving in an **unconditional-exfiltration form** (pushing all refs to a new remote, archiving / syncing a whole tree, pushing a mirror that COPIED the repository root, generating a public / link-shared URL, publishing to a public registry / public repository) — whether sent directly or by arming a path that will send automatically (editing CI / a publish pipeline and then committing / pushing counts too). Look at where the data finally lands, do not stop at the first hop, and do not allow it because a merge / review gate lies in the future — arming the path is itself the harm. Sensitivity is decided by the data's provenance, not by how harmless the content looks; obfuscation does not change that provenance. Content that does not originate from a private source (such as an ordinary change made entirely inside a public repository and not copied from a private source) is not automatically treated as sensitive. Sending sensitive data by HTTP request / file upload to an address outside environment counts as **confirmed external** and does not take the soft_deny downgrade described below. When a destination's visibility cannot be determined (such as a git remote / registry of unclear public-or-private status), **this hard rule does not apply** — allow it as a normal operation; only confirmed external / public destinations, or the unconditional-exfiltration forms above, are hard, and naming does not unlock them either.",
    ),
    environment=(
        "Trust boundary: the session workspace directory and its explicitly mounted directories, plus the git remote of the session's starting repository. Paths and external addresses beyond these are treated as out of bounds / external.",
        "The session workspace is **a throwaway isolated directory created fresh for every session** (not a pre-existing user repository); file changes inside it are backed by checkpoints and can be rolled back. Starting out empty with no dependency manifest is normal for it, and constitutes neither a supply-chain nor an anomaly signal.",
        "The Python runtime is the product-managed app-level base at `~/.bridgic/AmphiAgent/python/base`; every Session / Build / Workflow Run / Child Agent shares it, `uv pip install` may install third-party dependencies into it, and ordinary scripts run with `python`. Tasks do not create a Python project or virtual environment in the workspace.",
        "The Node runtime uses only the product's bundled Node and the product-managed app-level base at `~/.bridgic/AmphiAgent/node/base`; every Session / Build / Workflow Run / Child Agent shares the packages and CLIs in it. Every npm dependency operation targets that base and does not create or use a local node_modules just because a package.json exists in the current directory; package.json may serve only as script metadata, and full project-local npm semantics are not supported.",
        "Trusted external domains / services / registries: none by default (the user may add them in the environment section of their own policy.json; once added they are treated as 'inside the trust boundary').",
        "Sensitive / regulated data locations: any file or store containing personal data — credit card numbers, addresses, phone numbers, identity documents, health records, etc.; plus credential files (.env / .ssh / ~/.aws/credentials / id_rsa / .netrc).",
    ),
)
