"""The **data layer** of the classifier's safety policy: loads the four policy
sections — allow / soft_deny / hard_deny / environment — from one JSON file for the
classifier to build its system prompt from.

Design points:

* **Drives the classifier only; never touches the code-level hard red lines**: this
  policy only affects the LLM classifier's judgement. Deterministic denials in code
  ("wipe the system disk" and friends) are final **before** the classifier and are
  unaffected by this file — an unbypassable floor.
* **One global file per user**: ``~/.bridgic/AmphiAgent/policy.json`` by default,
  overridable with ``AMPHI_POLICY_FILE``. **Workspace (in-repo) files are never read**
  — that would let an untrusted repository slip in an allow exception and escalate.
* **Hot reload**: the policy file is read on every judgement (never cached), so
  editing the JSON takes effect on the next judgement with no restart.
* **Fail-safe (never fail-open)**: missing file / invalid JSON / schema mismatch /
  unknown key / no blocking rules → fall back to the **built-in default policy** and
  log it. It never crashes, and never loosens up because the configuration broke.
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Optional, Tuple

logger = logging.getLogger(__name__)

# The four sections of a policy file; a missing section is treated as an empty list.
_SECTIONS = ("allow", "soft_deny", "hard_deny", "environment")
_ENV_VAR = "AMPHI_POLICY_FILE"
_DEFAULT_PATH = Path.home() / ".bridgic" / "AmphiAgent" / "policy.json"
# When an entry has no colon, the title degrades to its first few characters (for display only; it
# takes no part in any decision).
_TITLE_FALLBACK_CHARS = 12


@dataclass(frozen=True)
class Policy:
    """One classifier safety policy. All four sections are immutable sequences of
    "natural-language entries"."""

    allow: Tuple[str, ...] = ()
    soft_deny: Tuple[str, ...] = ()
    hard_deny: Tuple[str, ...] = ()
    environment: Tuple[str, ...] = ()


def soft_deny_ids(policy: Policy) -> Tuple[str, ...]:
    """Stable identifiers for the ``soft_deny`` entries (``S1``…``Sn`` in order).

    This is the **only legal value domain** for the classifier's ``rule`` field when it
    answers ``ask``. The prompting surface is exactly these ``soft_deny`` categories,
    but the code used to validate ``rule`` not at all, so the model
    could invent categories that do not exist in the policy (an "external code
    execution" was observed in practice) and raise a dialog from them — letting the model
    expand the prompting surface without limit. The identifiers make that invariant
    checkable: not producing an identifier = nothing was really matched.

    They are generated by position rather than written into the policy file so as **not
    to burden the user**: their policy.json stays a plain array of strings, with the
    format unchanged."""
    return tuple(f"S{i}" for i in range(1, len(policy.soft_deny) + 1))


def soft_deny_title(policy: Policy, rule_id: str) -> str:
    """Identifier → that entry's short title (everything before the first colon), for
    the "why you are being asked" line on the approval card.

    Returns the identifier itself when it can't be resolved (invalid identifier / no
    colon in the entry) so the display layer is never blank."""
    ids = soft_deny_ids(policy)
    if rule_id not in ids:
        return rule_id
    text = policy.soft_deny[ids.index(rule_id)]
    for sep in ("：", ":"):
        head = text.split(sep, 1)[0]
        if head != text:
            return head.strip()
    return text[:_TITLE_FALLBACK_CHARS].strip()


def resolve_policy_path() -> Path:
    """The policy file path: ``AMPHI_POLICY_FILE`` overrides it, otherwise the global
    per-user default."""
    configured = os.environ.get(_ENV_VAR)
    if configured:
        return Path(configured).expanduser()
    return _DEFAULT_PATH


def load_policy(path: Optional[Path] = None) -> Policy:
    """Load the policy; every call reads from disk (editing the file takes effect on the
    next judgement). A missing file (= no configuration, which is normal) falls back to
    the built-in default silently; a file that exists but is invalid or has no blocking
    rules falls back with a warning (fail-safe — never loosen up because of a bad config).

    Not cached: ``judge`` calls this once per round, and reading a small file plus a json
    parse is negligible, in exchange for always-latest correctness — avoiding an mtime
    cache serving a stale policy under "rewritten within the same tick" or "deleted and
    recreated with the same mtime".
    """
    from ._default_policy import DEFAULT_POLICY  # imported lazily to avoid a circular dependency with this module

    p = path if path is not None else resolve_policy_path()
    try:
        present = p.is_file()
    except OSError:
        present = False
    if not present:
        # The default path not existing = no configuration, which is a normal path and not warned
        # about. But a user who **explicitly set** ``AMPHI_POLICY_FILE`` and yet points at nothing
        # (one directory level off, or the shell didn't expand ``~``) is in the "thought it was set,
        # it wasn't" situation — the same line of defence as "unknown key" below, and it must warn,
        # otherwise every custom hard_deny silently stops applying.
        if path is None and os.environ.get(_ENV_VAR):
            _warn(f"the path {_ENV_VAR} points to does not exist or is not a file: {p} — falling back to the built-in default policy")
        return DEFAULT_POLICY
    return _parse_policy_file(p, DEFAULT_POLICY)


def _parse_policy_file(p: Path, default: Policy) -> Policy:
    try:
        raw = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError, ValueError):
        _warn(f"policy file unreadable or the JSON is invalid: {p} — falling back to the built-in default policy")
        return default
    if not isinstance(raw, dict):
        _warn(f"policy file top level is not an object: {p} — falling back to the built-in default policy")
        return default
    # An unknown key (very likely a typo, e.g. hard-deny / hardDeny) → fall back to the defaults.
    # Otherwise a misspelled hard red line is silently discarded while the other sections still
    # apply — a dangerous "thought it was set, it wasn't".
    unknown = sorted(set(raw) - set(_SECTIONS))
    if unknown:
        _warn(f"policy file has unknown keys {unknown} (typo? valid keys: {list(_SECTIONS)}): {p} — falling back to the built-in default policy")
        return default
    sections = _coerce_sections(raw)
    if sections is None:
        _warn(f"a section of the policy file is not an array of strings: {p} — falling back to the built-in default policy")
        return default
    policy = Policy(**sections)
    # No soft_deny / hard_deny at all → the classifier will only ever allow grey-area calls (which
    # is the same as switching classifier blocking off). This is almost always a truncated or empty
    # file (e.g. {}) or a misunderstanding; fall back to the defaults (which include a complete
    # soft_deny) to avoid a silent fail-open.
    if not policy.soft_deny and not policy.hard_deny:
        _warn(
            f"policy file has no soft_deny / hard_deny blocking rules at all, so the classifier "
            f"cannot intercept grey-area operations: {p} — falling back to the built-in default "
            "policy (to allow everything, switch to the 'full access' execution mode instead)"
        )
        return default
    return policy


def _coerce_sections(raw: dict) -> Optional[Dict[str, Tuple[str, ...]]]:
    """Normalise the four sections into tuples of strings; a section that is not an array
    of strings → ``None`` (the caller falls back to the default).
    A missing or ``null`` section is treated as empty (which is legal); ``raw`` has
    already guaranteed only known keys are present."""
    out: Dict[str, Tuple[str, ...]] = {}
    for sec in _SECTIONS:
        val = raw.get(sec, [])
        if val is None:
            val = []
        if not isinstance(val, list) or not all(isinstance(x, str) for x in val):
            return None
        out[sec] = tuple(val)
    return out


def _warn(msg: str) -> None:
    """Warn about a policy downgrade. **Must go through logging** — the desktop daemon is
    launched by Electron and its logs land in ``~/.bridgic/AmphiAgent/logs``; bare stderr
    never reaches that file, which would make every one of these fail-safe warnings
    invisible in production (and they are the only hint of a "thought it was set, it
    wasn't")."""
    logger.warning("[policy] %s", msg)
